/**
 * SecretStorage wrapper for the only two secrets Whetstone holds: the user's
 * provider API key (ADR-004, BYO key) and the per-device Ed25519 signing key
 * used for ledger checkpoints (ADR-006). Key custody stays with the writer —
 * there is no account and no backend — and neither secret is ever logged,
 * written to the ledger, or sent in telemetry; both live in SecretStorage only.
 *
 * The device signing key is generated once (via the task-03 crypto surface) and
 * reused on every later read, so ledger checkpoints stay verifiable across
 * sessions. `hasApiKey()` is the "no key set" signal the consent gate (task 13)
 * uses to decide whether key setup is needed before the first egress.
 */

import { generateKeyPair, type Ed25519KeyPair } from './crypto';

/** SecretStorage key for the user's provider API key. */
export const API_KEY_SECRET = 'whetstone.providerApiKey';
/** SecretStorage key for the per-device Ed25519 signing keypair (JSON-encoded). */
export const SIGNING_KEY_SECRET = 'whetstone.deviceSigningKey';

/**
 * The slice of `vscode.SecretStorage` this wrapper needs. Declaring it
 * structurally keeps the module free of a `vscode` import (so it unit-tests in
 * pure Node, like the rest of `shared/`), while the live `SecretStorage`
 * satisfies it at the call site.
 */
export interface SecretStore {
  get(key: string): Thenable<string | undefined>;
  store(key: string, value: string): Thenable<void>;
  delete(key: string): Thenable<void>;
}

/** Typed get/set access to Whetstone's secrets, backed by SecretStorage. */
export class WhetstoneSecrets {
  constructor(private readonly store: SecretStore) {}

  /** The provider API key, or `undefined` if none has been set. */
  async getApiKey(): Promise<string | undefined> {
    return this.store.get(API_KEY_SECRET);
  }

  /** Store (or replace) the provider API key. */
  async setApiKey(key: string): Promise<void> {
    await this.store.store(API_KEY_SECRET, key);
  }

  /** Remove the provider API key. */
  async clearApiKey(): Promise<void> {
    await this.store.delete(API_KEY_SECRET);
  }

  /**
   * Whether a provider API key has been set. This is the "no key set" signal
   * the consent gate consumes: `false` before any key exists, `true` after one
   * is stored.
   */
  async hasApiKey(): Promise<boolean> {
    const key = await this.store.get(API_KEY_SECRET);
    return typeof key === 'string' && key.length > 0;
  }

  /**
   * The per-device Ed25519 signing key, generating and persisting it on first
   * use and returning the same keypair on every later read (ADR-006). The
   * actual keygen lives in the task-03 crypto surface; this only stores/loads.
   */
  async getOrCreateSigningKey(): Promise<Ed25519KeyPair> {
    const existing = parseKeyPair(await this.store.get(SIGNING_KEY_SECRET));
    if (existing) {
      return existing;
    }
    const keyPair = generateKeyPair();
    await this.store.store(SIGNING_KEY_SECRET, JSON.stringify(keyPair));
    return keyPair;
  }
}

/** Parse a stored signing-key blob, returning `undefined` if absent or invalid. */
function parseKeyPair(raw: string | undefined): Ed25519KeyPair | undefined {
  if (!raw) {
    return undefined;
  }
  try {
    const parsed = JSON.parse(raw) as Partial<Ed25519KeyPair>;
    if (typeof parsed.publicKey === 'string' && typeof parsed.privateKey === 'string') {
      return { publicKey: parsed.publicKey, privateKey: parsed.privateKey };
    }
  } catch {
    // A corrupt blob is treated as "no key" and regenerated by the caller.
  }
  return undefined;
}
